# Taken from https://github.com/fwcd/lighthouse-client-swift/blob/e9f345f1d936c917e520449e379c9c0f00cccbb2/.github/workflows/docs.yml

name: Generate DocC
on:
  push:
    branches: [main]
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Pages
        uses: actions/configure-pages@v1
      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: "5.6"
      - name: Generate DocC
        uses: fwcd/swift-docc-action@v1
        with:
          target: SwiftyRedis
          output: ./public
          transform-for-static-hosting: "true"
          disable-indexing: "true"
          hosting-base-path: swifty-redis
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy DocC
        uses: actions/deploy-pages@v1
